
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iek42
 */
public class Gui_UpdateUsers extends javax.swing.JFrame {
    private String email;
    private String password;
    private boolean oldEm;
    private boolean oldPass;
    LibrarianAction la = new LibrarianAction();

    /**
     * Creates new form UpdateUsers
     */
    public Gui_UpdateUsers(String email, String password) {
        this.email=email;
        this.password=password;
        initComponents();
    }
    public Gui_UpdateUsers(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        oldEmail_textbox = new javax.swing.JTextField();
        oldPassword_textbox = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        newEmail_textbox = new javax.swing.JTextField();
        newPassword_textbox = new javax.swing.JTextField();
        newEmail_checkbox = new javax.swing.JCheckBox();
        newPassword_checkbox = new javax.swing.JCheckBox();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JButton jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Update Account Page");

        jLabel2.setText("Old Email:");

        jLabel3.setText("Old Password:");

        oldEmail_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldEmail_textboxActionPerformed(evt);
            }
        });

        jLabel4.setText("New Email:");

        jLabel5.setText("New Password:");

        newEmail_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmail_textboxActionPerformed(evt);
            }
        });

        newEmail_checkbox.setText("Same as the previous");
        newEmail_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmail_checkboxActionPerformed(evt);
            }
        });

        newPassword_checkbox.setText("Same as the previous");
        newPassword_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassword_checkboxActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oldEmail_textbox)
                            .addComponent(oldPassword_textbox)
                            .addComponent(newEmail_textbox)
                            .addComponent(newPassword_textbox, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newEmail_checkbox)
                            .addComponent(newPassword_checkbox))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(oldEmail_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(oldPassword_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newEmail_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEmail_checkbox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newPassword_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPassword_checkbox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldEmail_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldEmail_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldEmail_textboxActionPerformed

    private void newEmail_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmail_checkboxActionPerformed
        // TODO add your handling code here:
        JCheckBox j = (JCheckBox) evt.getSource();
        if(j.isSelected()){
            oldEm=true;
        }else{
            oldEm=false;
        }
    }//GEN-LAST:event_newEmail_checkboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Gui_AdminMenu(email,password).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean success = false;
        String oldemail = oldEmail_textbox.getText();
        String oldpassword = oldPassword_textbox.getText();
        String newemail = newEmail_textbox.getText();
        String newpassword = newPassword_textbox.getText();
        
        //if new password or email is the same, just assign old value
        if(oldEm){
            newemail = oldemail;
        }
        
        if(oldPass){
            newpassword = oldpassword;
        }
        
        
        try {
            success = la.UpdateUser(newemail,newpassword);
            if (success) {
                JOptionPane.showMessageDialog(this, "Successfully, the account is updated on our database");
                oldEmail_textbox.setText("");
                oldPassword_textbox.setText("");
                newEmail_textbox.setText("");
                newPassword_textbox.setText("");
                email = newemail;
                password = newpassword;
            } else if (newemail.isEmpty()||newpassword.isEmpty()||oldemail.isEmpty()||oldpassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in the account's information for updating...");
            } else {
                JOptionPane.showMessageDialog(this, "Something went wrong... the account is not updated yet");
            }
        } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(this, "Class no found");
                            Logger.getLogger(Gui_UpdateUsers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
                                        JOptionPane.showMessageDialog(this, "sql exception");

            Logger.getLogger(Gui_UpdateUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void newPassword_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassword_checkboxActionPerformed
        // TODO add your handling code here:
        JCheckBox j = (JCheckBox) evt.getSource();
        if(j.isSelected()){
            oldPass=true;
        }else{
            oldPass=false;
        }

    }//GEN-LAST:event_newPassword_checkboxActionPerformed

    private void newEmail_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmail_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmail_textboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_UpdateUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_UpdateUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_UpdateUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_UpdateUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_UpdateUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox newEmail_checkbox;
    private javax.swing.JTextField newEmail_textbox;
    private javax.swing.JCheckBox newPassword_checkbox;
    private javax.swing.JTextField newPassword_textbox;
    private javax.swing.JTextField oldEmail_textbox;
    private javax.swing.JTextField oldPassword_textbox;
    // End of variables declaration//GEN-END:variables
}
